# Generated by Django 3.2.4 on 2021-06-28 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='day',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='blog',
            name='month',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='blog',
            name='year',
            field=models.TextField(default=0),
        ),
    ]
