# Generated by Django 3.2.4 on 2021-06-29 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_blog_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='day',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='blog',
            name='month',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='blog',
            name='url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='blog',
            name='year',
            field=models.IntegerField(default=0),
        ),
    ]
